name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: powershell

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: make
    - name: Run
      run: ./main
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
